version: 0.0.5#{build}
image: Visual Studio 2015
install:
- cmd: >-
    SET PATH=%PATH%;C:\Qt\5.6\msvc2015\bin

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"
build_script:
- cmd: >-
    lrelease OpenRCT2Launcher.pro

    qmake OpenRCT2Launcher.pro

    nmake

    mkdir build-Windows

    copy release\OpenRCT2.exe build-Windows\OpenRCT2.exe

    windeployqt build-Windows\OpenRCT2.exe

    copy compiled_libs\libeay32.dll build-Windows\libeay32.dll

    copy compiled_libs\ssleay32.dll build-Windows\ssleay32.dll

    pushd build-Windows & 7z a -tzip ..\OpenRCT2Launcher-win.zip * & popd

    choco install innosetup

    set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

    iscc installer.iss
artifacts:
- path: OpenRCT2Launcher-win.zip
  name: zip-archive
- path: OpenRCT2Launcher-win.exe
  name: exe-installer
deploy:
- provider: GitHub
  auth_token:
    secure: U+ZR9yj0ExiwkxNQ5o/zhtschZ/kktjWmTMilMfbHCcD0dlyBYDVUCjQWbQ8jiA7
  artifact: zip-archive, exe-installer
  on:
    appveyor_repo_tag: true